### ISSUE TITLE
Photovoltaic optimisation Data Package

### ISSUE THREAD

**Issue by zuzfil** [schoolofdata-ch/energy-data-ch#16]
Information and data resources on energy production for photovoltaic optimisation can be found here:
https://github.com/zuzfil/PV-Optimisation.

AEW Energie AG is an energy producer: https://www.aew.ch/.

**Comment by loleg** [comment]
@zuzfil thank you so much for your support here. Things got a bit chaotic in the last days, but we are cleared to go ahead and publish this open dataset. I'd like to see a few cosmetic improvements to it, in particular to focus on the data and not the challenge, i.e. to put it at the root of the repository and call it something appropriate. Then we could add a few Frictionless Data features to it, like a preview link and automatic validation badge. Would you like me to do this, or would you rather keep going here?

**Comment by loleg** [comment]
The challenge has been updated with the Data Package https://hack.opendata.ch/project/464 ~ thanks again @zuzfil !
