### ISSUE TITLE
Solar & Battery Combined System

### ISSUE THREAD

**Issue by loleg** [schoolofdata-ch/energy-data-ch#2]
This is a data set containing work data of an energy system in watt hours for each minute in a given year. The system is photovoltaic system combined with a lithium-ion battery with a capacity of 16.0 kWh. The data fields are _Discharge, Charge, Production, Consumption, Feed-in, From grid_

This `homeenergy` dataset including years 2016-2019 can be [found here ...](https://github.com/birdie82/homeenergy#solar--battery-combined-system)

**Comment by birdie82** [comment]
https://github.com/birdie82/homeenergy

**Comment by birdie82** [comment]
http://hack.opendata.ch/project/289

**Comment by birdie82** [comment]
http://hack.opendata.ch/project/283

**Comment by Vanya87** [comment]
The first two links do not work and provide error messages.

**Comment by loleg** [comment]
Indeed, @birdie82 could you please let us know if this data is still available?

Archiving for now as part of clean-up for [2020 event](https://hack.opendata.ch/event/31). Feel free to re-open the issue if you are interested and want to try to help open up this or similar data sources!
