### ISSUE TITLE
Aggregated load profiles of apartment blocks

### ISSUE THREAD

**Issue by birdie82** [schoolofdata-ch/energy-data-ch#3]
Die Daten stammen in einem vom BFE unterstützten, Forschungsprojekt zur Netzdienlichkeit von Wohngebäuden. Es sind die aggregierten Lastgänge von 20 Mehrfamilienhäusern (nach Möglichkeit mit separatem Allgemeinstrom) und so ingesamt 165 Wohnungen. Die Daten sind pro Gebäude in einem File enthalten.

[Weiter lesen ...](https://github.com/birdie82/aptblocks#aggregierte-messdaten-des-gesamten-geb%C3%A4ude)

**Comment by birdie82** [comment]
http://hack.opendata.ch/project/289

**Comment by birdie82** [comment]
http://hack.opendata.ch/project/286

**Comment by Vanya87** [comment]
The first link provides an error message.

**Comment by loleg** [comment]
Looks like the same missing repo problem as #2 

Archiving for now as part of clean-up for [2020 event](https://hack.opendata.ch/event/31). Feel free to re-open the issue if you are interested and want to try to help open up this or similar data sources!
