### ISSUE TITLE
Project VEiN

### ISSUE THREAD

**Issue by birdie82** [schoolofdata-ch/energy-data-ch#4]
Im Rahmen des Projektes VEiN (Verteilte Einspeisung in Niederspannungsnetze) werden im Niederspannungsnetz der TS Kreuzmatt in Rheinfelden mehrere Dezentrale Erzeugungsanlagen (DEA) betrieben. Das Ziel des Feldversuches VEiN ist, die Auswirkungen der vermehrten dezentralen Einspeisung auf die Netzqualität und auf den Betrieb von Niederspannungsnetzen in der Praxis zu ermitteln. Zudem dient das Projekt VEiN auch als Plattform für wissenschaftliche Versuche bezüglich der dezentralen Stromerzeugung.

[Weiter lesen ...](https://github.com/birdie82/vein/blob/master/README.md#projekt-vein)

**Comment by birdie82** [comment]
https://github.com/birdie82/vein

**Comment by birdie82** [comment]
http://hack.opendata.ch/project/290

**Comment by Vanya87** [comment]
The first two links provide error messages

**Comment by loleg** [comment]
Looks like the same missing repo problem as #2

Archiving for now as part of clean-up for [2020 event](https://hack.opendata.ch/event/31). Feel free to re-open the issue if you are interested and want to try to help open up this or similar data sources!
