### ISSUE TITLE
Climate Scenarios for Switzerland

### ISSUE THREAD

**Issue by loleg** [schoolofdata-ch/energy-data-ch#7]
The Swiss National Centre for Climate Services (NCCS) has made over a terabyte of data available for the Hackdays that deal with emissions and climate monitoring. These were the basis for several [publications](https://www.nccs.admin.ch/nccs/de/home/materialien-und-daten/daten/ch2018---klimaszenarien-fuer-die-schweiz.html) as well as an interactive [Webatlas](https://www.nccs.admin.ch/nccs/de/home/materialien-und-daten/daten/ch2018-webatlas.html).

_Sie können dort sowohl die 2km Gitter-Szenarien herunterladen als auch die Stations-Szenarien. Ich hänge Ihnen ausserdem auch eine Textdatei mit allen Stations-Metadaten an. Bitte beachten Sie auch die Nutzungsbedingungen der CH2018 Daten (https://www.nccs.admin.ch/nccs/de/home/materialien-und-daten/daten/ch2018---klimaszenarien-fuer-die-schweiz.html)._

**Comment by bkarolina** [comment]
I have created data package for this here: https://github.com/bkarolina/Climate-Scenarios-Switzerland

**Comment by loleg** [comment]
@bkarolina thank you so much for your support! Looking forward to see this Data Package used in challenges and projects ahead.
